This repo mainly consists of two part : the mesh generation part and the part for image compression.

# Mesh generation
This part is realized with Boyer-Waston algorithm. This part could be compiled by running 
```
cd src
make maketriangulation.make
```
which will generate an executable file named `triangulation`. By running this executable, you will obtain a `triangulation.mesh` file, which will contain the coordinate of vertices and the list of triangles. The `.mesh` file could be opened by `Vizir`.

# Image compression
This part is based on the mesh generation developed before. The compression is realized by storing the image using less pixel points. The number of pixel points can be specified by the user and the points are generated by the aforementioned mesh generation module. 

This part can be compiled by running 
```
cd src
make makecomprImage.make
```
This will generate an executable `comprImage`. By running this executable, you will obtain `triangulation.mesh`, `solCompr.sol` and `solQC.sol`. You could visualize the mesh by importing these three files into `Vizir`.